import type { TutorialData } from '~/data/mock'

export function useExporter() {

  function generateDriverSnippet(tutorial: TutorialData): string {
    const stepsCode = tutorial.steps.map(s => {
      const selector = s.confirmedSelector ?? s.suggestedSelector ?? 'body'
      return `  {
    element: '${selector}',
    popover: {
      title: '${escape(s.title)}',
      description: '${escape(s.instruction)}',
    },
  }`
    }).join(',\n')

    return `// Auto-generated by AnTrail
// Tutorial: ${tutorial.tutorialTitle}
// App:      ${tutorial.appName}
// Install:  npm install driver.js

import { driver } from 'driver.js'
import 'driver.js/dist/driver.css'

const tutorialDriver = driver({
  showProgress: true,
  animate: true,
  overlayColor: 'rgba(0, 0, 0, 0.75)',
  steps: [
${stepsCode}
  ],
})

// Call tutorialDriver.drive() to start the walkthrough.
// Example - trigger on a Help button click:
document.querySelector('#help-btn')?.addEventListener('click', () => {
  tutorialDriver.drive()
})`
  }

  function generateShepherdSnippet(tutorial: TutorialData): string {
    const stepsCode = tutorial.steps.map(s => {
      const selector = s.confirmedSelector ?? s.suggestedSelector ?? 'body'
      return `  {
    id: 'step-${s.stepNumber}',
    attachTo: { element: '${selector}', on: 'bottom' },
    title: '${escape(s.title)}',
    text: '${escape(s.instruction)}',
    buttons: [
      { text: 'Back', action: tour.back },
      { text: 'Next', action: tour.next },
    ],
  }`
    }).join(',\n')

    return `// Auto-generated by AnTrail (Shepherd.js)
// Install: npm install shepherd.js

import Shepherd from 'shepherd.js'
import 'shepherd.js/dist/css/shepherd.css'

const tour = new Shepherd.Tour({
  useModalOverlay: true,
  defaultStepOptions: { cancelIcon: { enabled: true } },
})

tour.addSteps([
${stepsCode}
])

tour.start()`
  }

  function generateJSON(tutorial: TutorialData): string {
    return JSON.stringify(tutorial, null, 2)
  }

  async function copyToClipboard(text: string): Promise<boolean> {
    try {
      await navigator.clipboard.writeText(text)
      return true
    } catch {
      return false
    }
  }

  function downloadFile(content: string, filename: string, type = 'text/javascript') {
    const blob = new Blob([content], { type })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  return {
    generateDriverSnippet,
    generateShepherdSnippet,
    generateJSON,
    copyToClipboard,
    downloadFile,
  }
}

function escape(str: string) {
  return str.replace(/'/g, "\\'")
}
